language: R
dist: bionic
cache: packages


# ----------------+-------------+---------+-------+--------------+-------------+
# Environment     | R CMD CHECK | codecov | lintr | goodpractice | rough tests |
# ----------------+-------------+---------+-------+--------------+-------------+
# MacOS           | No          | No      | Yes   | No (*)       | No          |
# Linux r-devel   | Yes         | Yes     | No    | No           | No          |
# Linux r-release | No          | No      | No    | No           | Yes         |
# ----------------+-------------+---------+-------+--------------+-------------+
#
# (*) Would love to, but it takes >30 mins on MacOS
#

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  #- r: release
  #  os: osx


r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick@6; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"

script:
  - echo "Do nothing"
